name: autonomous-agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytest>=7.0.0
  - pytest-asyncio>=0.21.0
  - pytest-flask>=1.3.0
  - bandit>=1.7.0
  - safety>=2.0.0
  - flake8>=6.0.0
  - coverage>=7.0.0
  - numpy>=1.21.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - networkx>=3.0
  - requests>=2.25.0
  - flask>=2.0.0
  - werkzeug>=2.0.0
  - pyyaml>=6.0
  - jsonschema>=4.0.0
  - black>=22.0.0
  - isort>=5.0.0
  - mypy>=0.910
  - jupyter>=1.0.0
  - ipython>=8.0.0
  - notebook>=6.4.0
  - pip
  - pip:
    - tiktoken>=0.5.0
    - aiofiles>=23.0.0
    - aiosqlite>=0.21.0
    - py2neo>=2021.2.4
    - neo4j>=5.0.0
    - pytest-cov>=4.0.0
    - pytest-mock>=3.10.0
    - pytest-xdist>=3.0.0
    - markdown-it-py>=3.0.0
    - rich>=14.0.0
    - stevedore>=5.4.0
